version: "3"

services:
  facts-gradechecker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - facts-gradechecker_data:/app/data

volumes:
  facts-gradechecker_data: